{
	"version": 1779890469,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/chirpy-sheet0.png",
		"images/chirpy-sheet1.png",
		"images/chirpy-sheet2.png",
		"images/combosprite-sheet0.png",
		"images/combosprite-sheet1.png",
		"images/combosprite-sheet2.png",
		"images/inputtext.png",
		"images/scoreboard-sheet0.png",
		"images/typingboard-sheet0.png",
		"images/background-sheet0.png",
		"images/background-sheet1.png",
		"images/background-sheet2.png",
		"images/background-sheet3.png",
		"images/logo-sheet0.png",
		"images/txtfeedbackright.png",
		"images/playbtn-sheet0.png",
		"images/hand-sheet0.png",
		"images/txtfeedbackwrong.png",
		"images/txtfeedbackaware.png",
		"media/furin summer loop.m4a",
		"media/furin summer loop.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"dictionary.json"
	]
}